### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by one-aalam** [one-aalam/attic#1]
**Primary Tasks**
- [ ] Integrate https://mjml.io/ for beautiful, on-demand mailing
- [ ] Integrate https://github.com/graphile/worker for background jobs
- [ ] Add social (non-passport) authentications for Gmail, Facebook and Github
- [ ] Add Dockerfile
- [ ] Re-factor, clean-up and see if there's community favored, more robust stuff that could be plugged-in
- [ ] Logo
- [ ] Documentation
- [ ] CI Integration
- [ ] Call it a day!

**Secondary Task**
Separate branches that will build over the stabilized architecture
- [ ] TypeGraphQL https://typegraphql.ml/
- [ ] Dependency Inversion

**Auxillary Tasks**
- [ ] Explore libraries offered by https://github.com/typestack and see if they are a promising option to provide a more robust base
- [ ] Monolith --> Micro-services and everything that requires!
- [ ] Kubernetes
